# Esse programa é um bot de automação, então é muito provável que a conta e o CNPJ utlizados sejam banidos após pouco tempo de uso. Portanto, utilize uma conta anônima e temporária.
#
# NÃO UTILIZE SUA CONTA PESSOAL
# NÃO UTILIZE O CNPJ DA SUA EMPRESA, é altamente provável que ele será banido!
#
# 1. Adquira um email temporário em https://temp-mail.org/
# - salve este email no campo `username` abaixo
#
# 2. Adquira um CNPJ aleatório em https://www.4devs.com.br/gerador_de_cnpj
# - esse CNPJ será utilizado apenas cara criar a conta
#
# 3. Crie uma conta empregos.com acessando em https://b2b.empregos.com.br/empresa/cadastro/comecar-cadastro
# - insira um nome e sobrenome qualquer
# - insira um número de celular qualquer
# - selecione o cargo 'Gerente de recrutamento e seleção'
# - selecione 'Para minha empresa'
# - insira o endereço de mail adquirido no primeiro passo
# - crie uma senha e salve ela no campo `password` abaixo
# - avance para a próxima fase e insira o CNPJ aleatório adquirido anteriormente
# - avance para a próxima etapa e preencha os campos aleatóriamente
# - clique em continuar / criar / avançar para concluir o cadastro
#
# 4. Pronto, agora você já tem uma conta temporária Empregos.com e pode utilizá-la sem medo de sofrer qualquer sanção.
# - ATENÇÃO: a conta criada é temporária e tem duração de 24h. Você precisará repetir os passos anteriores diariamente!
# - Observação: Caso você não queira criar uma conta todos os dias, você pode criar um email permanente e anônimo usando ProtonMail, mas você precisará cadastrar um número de telefone particular seu para fins de autenticação.
#
# 5. Insira abaixo o email e senha criados nos passos anteriores
login:
  username: "example@protonmail.com" # email
  password: "example.password"

# Os termos dos filtros devem ser exatamente iguais aos exibidos no site:
# - devem respeitar capitalização (maiúscula / minúscula)
# - devem respeitar acentuação
# - devem respeitar espaçamento
search:
  job_roles: ["Administrativo"] # lista de cargos desejados. Ex: promotor, consultor comercial'
  locations: ["Osasco, SP"] # lista de localizações para efetuar a busca. Exemplo: "Salvador, BA", "Osasco, SP"
  disabilities: # lista de deficiências que a serem buscadas (caso não encontras, pula a próxima)
    [
      # "Pessoa com deficiência visual", # worker 2
      "Pessoa com deficiência física", # worker 1
      "Pessoa com deficiência auditiva",
      "Pessoa com deficiência",
      "Pessoa com deficiência mental",
      "Pessoa com deficiência múltipla",
    ]

download:
  timeout: 5000 # tempo limite total (em mili-segundos) que download de cada .pdf pode levar. Quando o tempo limite for excedido, uma nova tentativa será executada. Padrão = 5000
  retry_limit: 5 # a quantidade de vezes que o programa tentará baixar o mesmo .pdf antes de ir para o próximo. Padrão = 5
  ask_confirmation: True # se deve ou não pedir confirmação antes de iniciar um pacote de downloads. Padrão = True
  cache_duration: 24 # o tempo de duração do cache (em horas). Caso um download seja repetido, ao invés de acessar o site, ele acessa o banco de dados local. Evita acessos desnecessários ao site, e aumenta significativamente a velocidade de execução do programa. Padrão = 6
  output_dir: "output/" # O endereço da pasta que receberá os documentos .pdf

debug_mode:
  enabled: False # quanto ativado, limita as quantidades de páginas acessadas e de documentos baixados
  search_page_limit: 1
  cv_download_limit: 5
